feat: implement release container/binary signing (#269)
related:
- https://github.com/axelarnetwork/axelar-core/pull/1210
- https://github.com/axelarnetwork/axelar-core/pull/1022

diff --git a/.github/workflows/build-docker-image-and-binaries.yaml b/.github/workflows/build-docker-image-and-binaries.yaml
--- a/.github/workflows/build-docker-image-and-binaries.yaml
+++ b/.github/workflows/build-docker-image-and-binaries.yaml
@@ -16,13 +16,34 @@ jobs:
           - ubuntu-18.04
     runs-on: ${{ matrix.os }}
 
+    permissions:
+      contents: write
+      packages: write
+      id-token: write
+
     steps:
+      - name: Validate tag
+        env:
+          SEMVER: ${{ github.event.inputs.tag }}
+        run: |
+          if [[ $SEMVER =~ v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3} ]]; then echo "Tag is okay" && exit 0; else echo "invalid tag" && exit 1; fi
+
       - name: Checkout code
         uses: actions/checkout@v2
         with:
           fetch-depth: '0'
           ref: ${{ github.event.inputs.tag }}
           submodules: recursive
+
+      - name: Install Cosign
+        uses: sigstore/cosign-installer@main
+
+      - name: Import GPG key
+        id: import_gpg
+        uses: crazy-max/ghaction-import-gpg@v4
+        with:
+          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
+          passphrase: ${{ secrets.GPG_PASSPHRASE }}
 
       - name: Install SSH key
         uses: webfactory/ssh-agent@v0.4.1
@@ -39,6 +60,13 @@ jobs:
         run: |
           make copy-binary-from-image
 
+      - name: Sign Binaries
+        working-directory: ./bin
+        env:
+          SEMVER: ${{ github.event.inputs.tag }}
+        run: |
+          gpg --armor --detach-sign  tofnd-linux-amd64-v${SEMVER}
+
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
@@ -49,6 +77,12 @@ jobs:
         run: |
           docker tag axelar/tofnd:latest axelarnet/tofnd:${{ github.event.inputs.tag }}
           docker push axelarnet/tofnd:${{ github.event.inputs.tag }}
+
+      - name: Sign the images with GitHub OIDC
+        run: cosign sign --oidc-issuer https://token.actions.githubusercontent.com ${TAGS}
+        env:
+          TAGS: axelarnet/tofnd:${{ github.event.inputs.tag }}
+          COSIGN_EXPERIMENTAL: 1
 
       - name: Upload binaries to release
         uses: svenstaro/upload-release-action@v2
